apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: k8strain
spec:
  selector:
    name: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  sessionAffinity: None

