apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8strain-files-pv
spec:
  capacity:
    storage: 4096Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.23.30.63
    path: "/mnt/vol01/caicloud/"
